spring:
  mvc.view:
    prefix: /jsp-views/
    suffix: .jsp
  resources:
    static-locations: /html/
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari.maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
